defaults:
  - _self_
  - network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

robot_cam_serial_numbers:
  - 1: '239122072217'
  - 2: '023322062082' # this is actually 2
  - 3: '233522071078' # this is actually 3
  - 4: '141722076049'

robot_cam_depth_activated:
  - 1: True
  - 2: True 
  - 3: True 
  - 4: True 
  
cam_configs:
  width: 640 
  height: 480 
  fps: 30
  processing_preset: 1 # High accuracy mode
  rotation_angle: 0

oculus_cam: 0 # First camera
num_cams: 1

hydra:  
  output_subdir: null  
  run:  
    dir: .
