defaults:
  - _self_
  - camera
  - network
  - robot: xarm_stick
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

storage_path: /mnt/robotlab/enes/3dtouch/04.20.2024/
demo_num: 1
sim_env: false
is_xela: false
host: ${host_address}



hydra:  
  output_subdir: null  
  run:  
    dir: .
