
preprocessor_module:
  _target_: openteach.preprocess.Preprocessor
  data_path: extracted_data/pick/ # Path to the extracted data
  modules:
    robot: ${robot_cfg}
    image: ${image_cfg}
  dump_data_indices: true
  process_single_demo: false

robot_cfg:
  _target_: openteach.preprocess.RobotPreprocessor
  subsample_separately: true
  robot_names: ['xarm']
  robot_thresholds: # If robot thresholds are set to 0 then it will basically not subsample
    arm: 10 

image_cfg:
  _target_: openteach.preprocess.ImagePreprocessor
  camera_id: 0
  is_ssl: false
  time_difference: 1 # If the there is no set time difference we will not apply preprocessing for images

